# Generated by Django 4.1.3 on 2022-12-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='state',
            field=models.CharField(default='Ceara', max_length=100, verbose_name='estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='city',
            field=models.CharField(max_length=100, verbose_name='cidade'),
        ),
    ]
