# Generated by Django 4.1.3 on 2022-12-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_baseuser_state_alter_baseuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='name',
            field=models.CharField(default='Cleber', max_length=200, verbose_name='nome'),
            preserve_default=False,
        ),
    ]
