# Generated by Django 4.1.3 on 2022-12-06 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.blood_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='peso')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='altura')),
                ('blood_type', models.CharField(choices=[(utils.blood_types.BloodTypeEnum['A_NEG'], utils.blood_types.BloodTypeEnum['A_NEG']), (utils.blood_types.BloodTypeEnum['A_POS'], utils.blood_types.BloodTypeEnum['A_POS']), (utils.blood_types.BloodTypeEnum['B_NEG'], utils.blood_types.BloodTypeEnum['B_NEG']), (utils.blood_types.BloodTypeEnum['B_POS'], utils.blood_types.BloodTypeEnum['B_POS']), (utils.blood_types.BloodTypeEnum['O_NEG'], utils.blood_types.BloodTypeEnum['O_NEG']), (utils.blood_types.BloodTypeEnum['O_POS'], utils.blood_types.BloodTypeEnum['O_POS']), (utils.blood_types.BloodTypeEnum['AB_NEG'], utils.blood_types.BloodTypeEnum['AB_NEG']), (utils.blood_types.BloodTypeEnum['AB_POS'], utils.blood_types.BloodTypeEnum['AB_POS'])], max_length=10)),
            ],
        ),
    ]
