# Generated by Django 4.1.3 on 2022-12-11 15:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contract_date', models.DateField(verbose_name='data do contrato')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='salário')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('crm', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="CRM deve estar no formato: 'CRM/UF XXXXXX'.", regex='^CRM\\/[A-Z][A-Z] d{6}$')], verbose_name='crm (formato CRM/UF XXXXXX)')),
                ('specialty', models.CharField(max_length=100, verbose_name='especialidade')),
            ],
        ),
    ]
