# Generated by Django 4.1.3 on 2022-12-13 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_doctor_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='crm',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="CRM deve estar no formato: 'CRM/UF XXXXXX'.", regex='^CRM/[A-Z]{2} \\d{6}$')], verbose_name='crm (formato CRM/UF XXXXXX)'),
        ),
    ]
