# Generated by Django 4.1.3 on 2022-12-13 02:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_doctor_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100, verbose_name='especialidade')),
                ('date', models.DateField(verbose_name='data')),
                ('time', models.CharField(choices=[(8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00')], max_length=10, verbose_name='hora')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Número de telefone deve conter 11 dígitos: '(XX) XXXXX XXXX'.", regex='^\\d{11}$')], verbose_name='telefone')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.doctor')),
            ],
        ),
    ]
